config/routes.rb
Checkmate::Application.routes.draw do
  match '/redeem_invite/:code' => 'users#new', :as => 'redeem_invitation'

  resources :passwords, :only => [:new, :create]

  resources :users do
    resource :password, :only => [:edit, :update]
  end

  resource :session, :only => [:new, :create, :destroy]
  
  resource :invite, :only => [:new, :create]

  root :to => 'users#new'
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  attr_accessible :email, :user_id

  belongs_to :user

  validates :email,
            :presence => true,
            :email => true

  validates :user_id,
            :presence => true,
            :numericality => true

  before_validation :generate_code, :on => :create
  after_save :deliver, :on => :create

  def generate_code
    self.code = Digest::SHA1.hexdigest("--#{Time.now.utc.to_s}--#{self.email}--")
  end

  def deliver
    InviteMailer.invite(self).deliver
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include SimplestAuth::Model
  authenticate_by :email

  attr_accessible :email, :password, :password_confirmation, :avatar

  has_many :invites
  
  validates :email,
            :presence => true,
            :uniqueness => true,
            :email => true
  validates :password, :confirmation => true
  validates :password, :length => { :minimum => 5 }, :if => :password_required?
  validates :password, :password_confirmation, :presence => true, :on => :create
  validates :password_reset_token, :uniqueness => true, :allow_nil => true

  mount_uploader :avatar, AvatarUploader

  def set_password_reset_token
    update_attribute(:password_reset_token, SecureRandom.uuid)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SimplestAuth::Controller
  protect_from_forgery

  private

  def ensure_logged_in
    unless logged_in?
      redirect_to new_session_path, :alert => "You must login first"
    end
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_filter :ensure_logged_in
  
  def new
  end

  def create
    invite = Invite.new(params[:invite])
    invite.user = current_user
    if invite.save
      redirect_to root_path, :notice => "Invitation sent"
    else
      flash.now[:error] = "Invalid email address. Try again."
      render "new"
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  def new
  end

  def create
    # TODO add email index to users table
    user = User.find_by_email(params[:user][:email])

    if user
      user.set_password_reset_token
      PasswordResetMailer.send_reset_instructions(user).deliver
      redirect_to root_path, :notice => "Check your email for reset instructions"
    else
      flash.now[:error] = "No user was found for the given email address"
      render :new
    end
  end

  def edit
    @user = User.find_by_password_reset_token(params[:token]) if params[:token].present?

    unless @user
      redirect_to new_password_path, :alert => "Invalid reset token"
    end

    self.current_user = @user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:user][:email], params[:user][:password])
      self.current_user = user
      redirect_to user_path(user), :notice => "Signed in"
    else
      redirect_to new_session_path, :alert => "Couldn't find a user with those credentials"
    end
  end

  def destroy
    self.current_user = nil
    redirect_to new_session_path, :alert => "Signed out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    if params[:code]
      invite = Invite.find_by_code(params[:code])
      @user = User.new(:email => invite.email)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      self.current_user = @user
      redirect_to user_path(@user), :notice => "You signed up!"
    else
      flash.now[:error] = "There were errors with your submission"
      render "new"
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.assign_attributes(params[:user])
    if @user.save
      redirect_to edit_user_path(@user.id), :notice => "Information updated"
    else
      redirect_to edit_user_path(@user.id), :alert => "There were errors with your submission"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/invites/new.html.erb
<%= simple_form_for :invite, :url => invite_path do |f| %>
  <%= f.input :email %>
  <%= f.button :submit, :value => 'Send Invite' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checkmate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? %>
  <%= link_to "Edit Account", edit_user_path(current_user) %> or 
  <%= link_to "Invite a Friend", new_invite_path %> or 
  <%= link_to "Logout", session_path, :method => :delete %>
<% else %>
  <%= link_to "Login", new_session_path %> or 
  <%= link_to "Signup", new_user_path %>
<% end %>

<% flash.each do |key,value| %>
  <% if value.present? %>
    <div class="flash">
      <%= value %>
    </div>
  <% end %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<%= simple_form_for :user, :url => user_path, :method => :put, :html => { :multipart => true } do |f| %>
  <%= image_tag(@user.avatar_url) if @user.avatar? %>
  <%= f.file_field :avatar %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit, :value => 'Update Information' %>
<% end %>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.file_field :avatar %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit, :value => 'Sign Up' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<%= image_tag(@user.avatar_url) if @user.avatar? %>